Params:
  baseURL: https://rtrigg.github.io
  languageCode: 'en-us'
  title: 'My Tech Blog'
  themesDir: 'themes'
  theme: 'pixyll'
  contentdir: 'content'
  publishdir: 'public'

[indexes]
  category = 'categories'
  tag = 'tags'

[params]
  paginate = true
